### ISSUE TITLE
VS code ipynb notebooks

### ISSUE THREAD

**Issue by theosanderson** [jmcbroome/BTE#13]
I turned to my other setup, Linux under WSL, created a conda environment and installed BTE.

I can run `python` and type `import bte` successfully.

I tend do do a lot of my initial development in ipynb notebooks, through VS Code.

When I try to do that I get this error:
![image](https://user-images.githubusercontent.com/19732295/215354010-61335762-8611-4576-82c4-d7d69b41f383.png)

**Comment by jmcbroome** [comment]
Ugh, this error. This was a recurrent problem where exit was imported by some interpreters but not others. [I actually updated the source code to explicitly refer to sys.exit()](https://github.com/jmcbroome/BTE/commit/27f73046646d76db06fdf714e5255b62acc0b1e6), which is in the latest release on Github. I think this release wasn't properly propagated to bioconda, for whatever reason, so I need to look into that. I assume you're on version 0.8.3?

**Comment by theosanderson** [comment]
I am indeed on 0.8.3. Great to here that is fixed on master, I'll consider that.

That explains why when I looked at the source I couldn't figure what was going on :)

**Comment by jmcbroome** [comment]
Note: it appears that the autobump never triggered and I didn't check on it like I should have, so it fell through the cracks. I've manually opened the pull request to get the BTE build on Bioconda on v0.8.4. Thanks
