### ISSUE TITLE
zsh: segmentation fault

### ISSUE THREAD

**Issue by qjabiri** [jmcbroome/BTE#20]
Whenever I try to use the remove.node() function I get this error, zsh: segmentation fault. Has anyone else encountered it and if so how did you solve it.

**Comment by jmcbroome-linkcell** [comment]
I suspect this isn't a bug, just a misunderstanding. `segmentation fault` indicates that you've attempted to access something in memory that isn't there anymore, or never was there. Node removal is recursive- if you delete a parent node, it also deletes all that node's children, and their children's children. If you then try to access a child node of the parent you deleted, it will not be there and you may get a `segmentation fault` error. You should start by checking your code logic and make sure you're only accessing objects that should still exist in memory. 

If you do think its a bug, I'm going to need a lot more context and a reproducible code example so I can replicate and track down the issue.

**Comment by jmcbroome** [comment]
I suspect this isn't a bug, just a misunderstanding. segmentation fault indicates that you've attempted to access something in memory that isn't there anymore, or never was there. Node removal is recursive- if you delete a parent node, it also deletes all that node's children, and their children's children. If you then try to access a child node of the parent you deleted, it will not be there and you may get a segmentation fault error. You should start by checking your code logic and make sure you're only accessing objects that should still exist in memory.

If you do think its a bug, I'm going to need a lot more context and a reproducible code example so I can replicate and track down the issue.
